<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SHAURYA" failures="0" tests="5" name="testngexamples.Example2" time="2.028" errors="1" timestamp="2023-05-22T15:54:36 IST" skipped="4">
  <testcase classname="testngexamples.Example2" name="testcase1" time="0.000">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <system-out/>
  <testcase classname="testngexamples.Example2" name="testcase2" time="2.028">
    <error message="Method testngexamples.Example2.testcase2() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testngexamples.Example2.testcase2() didn't finish within the time-out 2000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:266)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:64)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testcase2 -->
  <system-out/>
  <testcase classname="testngexamples.Example2" name="testcase1" time="0.000">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <system-out/>
  <testcase classname="testngexamples.Example2" name="testcase3" time="0.000">
    <skipped/>
  </testcase> <!-- testcase3 -->
  <system-out/>
  <testcase classname="testngexamples.Example2" name="testcase1" time="0.000">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <system-out/>
</testsuite> <!-- testngexamples.Example2 -->
